sum-bleu:
	./sum_bleu.sh ~/Library/Caches/bleu_none.out ~/Library/Caches/bleu_none_sum 10

run-bleu:
	./runBLEU.sh ~/Library/Caches/p3_gold_extract ~/Library/Caches/nbest_none 10

extract-nbest:
	./extract-per-nbest.sh ~/Library/Caches/P3_NBestList ~/Library/Caches/nbest_none 100

extract-n-lines:
	./extract-n-lines.sh ~/Library/Caches/p3_gold ~/Library/Caches/p3_gold_extract
